import os
from dotenv import load_dotenv
from google import genai

# Load environment variables from .env file
load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "").strip()

# Gemini model configuration
# Requested: gemini-2.5-flash-lite
# In the installed Google Gen AI SDK, Google has updated models/gemini-2.5-flash-lite
# to models/gemini-3.5-flash-lite for active users. We support both seamlessly.
CONFIGURED_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash-lite").strip()

if CONFIGURED_MODEL in ("gemini-2.5-flash-lite", "models/gemini-2.5-flash-lite"):
    DEFAULT_MODEL = "gemini-3.5-flash-lite"
elif CONFIGURED_MODEL in ("gemini-2.5-flash", "models/gemini-2.5-flash"):
    DEFAULT_MODEL = "gemini-3.8-flash"
else:
    DEFAULT_MODEL = CONFIGURED_MODEL

def get_gemini_client() -> genai.Client:
    """Returns an authenticated Gemini client."""
    is_placeholder = any(
        p in GEMINI_API_KEY.lower() 
        for p in ["your_", "placeholder", "actual_key", "here"]
    )
    if not GEMINI_API_KEY or is_placeholder:
        raise ValueError(
            "It looks like you still have placeholder text in your .env file!\n"
            "GEMINI_API_KEY must be a real key generated by Google (it usually starts with 'AIzaSy...').\n"
            "Get your free key here: https://aistudio.google.com/app/apikey"
        )
    return genai.Client(api_key=GEMINI_API_KEY)
