import os
from dotenv import load_dotenv
from google import genai

# Load environment variables from .env file (checks both backend dir and project root)
_env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
if os.path.exists(_env_path):
    load_dotenv(dotenv_path=_env_path, override=True)
else:
    load_dotenv(override=True)

def get_gemini_api_key() -> str:
    if os.path.exists(_env_path):
        load_dotenv(dotenv_path=_env_path, override=True)
    else:
        load_dotenv(override=True)
    return os.getenv("GEMINI_API_KEY", "").strip()

GEMINI_API_KEY = get_gemini_api_key()

CONFIGURED_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash-lite").strip()
if CONFIGURED_MODEL in ("gemini-2.5-flash-lite", "models/gemini-2.5-flash-lite"):
    DEFAULT_MODEL = "gemini-3.5-flash-lite"
elif CONFIGURED_MODEL in ("gemini-2.5-flash", "models/gemini-2.5-flash"):
    DEFAULT_MODEL = "gemini-3.8-flash"
else:
    DEFAULT_MODEL = CONFIGURED_MODEL

def get_gemini_client() -> genai.Client:
    """Returns an authenticated Gemini client."""
    api_key = get_gemini_api_key()
    is_placeholder = any(
        p in api_key.lower() 
        for p in ["your_", "placeholder", "actual_key", "here"]
    )
    if not api_key or is_placeholder:
        raise ValueError(
            "It looks like you still have placeholder text in your .env file!\n"
            "GEMINI_API_KEY must be a real key generated by Google (it usually starts with 'AIzaSy...').\n"
            "Get your free key here: https://aistudio.google.com/app/apikey"
        )
    return genai.Client(api_key=api_key)
